apiVersion: v1
entries:
  payment:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-25T11:49:53.396259813Z"
    description: A Helm chart for Kubernetes
    digest: 87313eb90043cb87080d7250faea0aa81a258e668fc76b4fa15cfbefafbfeaf5
    name: payment
    type: application
    urls:
    - https://Kalyani-Bambal.github.io/helm-repo/charts/payment-0.1.0.tgz
    version: 0.1.0
  shipping:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-25T11:49:53.396632989Z"
    description: A Helm chart for Kubernetes
    digest: bf32c60a66a548eb6084aa092ccaf78a4e5450bdff571c247898e0ddc3cfe932
    name: shipping
    type: application
    urls:
    - https://Kalyani-Bambal.github.io/helm-repo/charts/shipping-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-25T11:49:53.39556088Z"
