apiVersion: v1
entries:
  payment:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-25T11:41:59.192055792Z"
    description: A Helm chart for Kubernetes
    digest: 7e7198a5ee4da85ff9f3c723469fa0ff99feb23bea33f5e5168a00713ae4792b
    name: payment
    type: application
    urls:
    - https://Kalyani-Bambal.github.io/helm-repo/charts/payment-0.1.0.tgz
    version: 0.1.0
  shipping:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-25T11:41:59.192253937Z"
    description: A Helm chart for Kubernetes
    digest: 30faa86080d25247bb0a8895826c784398c585b1decca2d705cde469bda9537c
    name: shipping
    type: application
    urls:
    - https://Kalyani-Bambal.github.io/helm-repo/charts/shipping-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-25T11:41:59.191754833Z"
